services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      #- ../persisted-data/uploads:/app/uploads  Carpeta donde se almacenan las imágenes
      - /var/pedidos_data/uploads:/app/uploads
    devices:
      - '/dev/ttyS3:/dev/ttyS3'
    environment:
      DATABASE_URL: mysql://root:pedidospassword@sistema_pedidos_back:3306/sistema_pedidos
    networks:
      - shared_network
    privileged: true

networks:
  shared_network:
    external: true
