services:
  db:
    image: mysql:8.0-debian
    container_name: sistema_pedidos_back
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pedidospassword
      MYSQL_DATABASE: sistema_pedidos
      MYSQL_USER: nestuser
      MYSQL_PASSWORD: pedidospassword
    volumes:
      - mysql_data:/var/lib/mysql # Volumen para persistir datos
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  mysql_data: # Define el volumen (Docker lo gestiona automáticamente)
